// 物品配置模块
// 定义所有可用物品的属性

const ITEMS_CONFIG = {
  // === 消耗品 ===
  油桶: {
    name: "油桶",
    color: "#eab308",
    description: "一桶汽油，可以为皮卡补充燃油。",
    weight: 8,
    category: "consumable",
    useEffect: { fuel: 30 },
    stackable: true,
  },
  修理包: {
    name: "修理包",
    color: "#22c55e",
    description: "简易修理工具，可以修复皮卡的损伤。",
    weight: 5,
    category: "consumable",
    useEffect: { durability: 25 },
    stackable: true,
  },
  坐垫: {
    name: "坐垫",
    color: "#a78bfa",
    description: "柔软的坐垫，让乘客更舒适。",
    weight: 3,
    category: "consumable",
    useEffect: { comfort: 20 },
    stackable: true,
  },
  急救箱: {
    name: "急救箱",
    color: "#f87171",
    description: "应急医疗用品，可以同时恢复耐久和舒适。",
    weight: 4,
    category: "consumable",
    useEffect: { durability: 10, comfort: 15 },
    stackable: true,
  },
  零食: {
    name: "零食",
    color: "#fb923c",
    description: "美味的零食，让旅途更愉快。",
    weight: 1,
    category: "consumable",
    useEffect: { comfort: 10 },
    stackable: true,
  },
  高级燃油: {
    name: "高级燃油",
    color: "#facc15",
    description: "高品质燃油，恢复大量燃油。",
    weight: 10,
    category: "consumable",
    useEffect: { fuel: 50 },
    stackable: true,
  },

  // === 材料 ===
  废金属: {
    name: "废金属",
    color: "#9ca3af",
    description: "可以用来制作修理工具的废旧金属。",
    weight: 3,
    category: "material",
    stackable: true,
  },
  布料: {
    name: "布料",
    color: "#c4b5fd",
    description: "柔软的布料，可以制作坐垫。",
    weight: 1,
    category: "material",
    stackable: true,
  },
  草药: {
    name: "草药",
    color: "#4ade80",
    description: "路边采集的草药，可以制作急救用品。",
    weight: 1,
    category: "material",
    stackable: true,
  },
  空罐: {
    name: "空罐",
    color: "#78716c",
    description: "空的金属罐，可以用来装燃油。",
    weight: 2,
    category: "material",
    stackable: true,
  },
  原油: {
    name: "原油",
    color: "#854d0e",
    description: "粗炼的原油，可以加工成燃油。",
    weight: 4,
    category: "material",
    stackable: true,
  },

  // === 特殊物品 ===
  幸运符: {
    name: "幸运符",
    color: "#34d399",
    description: "据说能带来好运的护身符。",
    weight: 1,
    category: "special",
    stackable: false,
  },
  八音盒: {
    name: "八音盒",
    color: "#f472b6",
    description: "会播放悠扬旋律的八音盒，大幅提升舒适度。",
    weight: 2,
    category: "consumable",
    useEffect: { comfort: 35 },
    stackable: false,
  },
  精炼剂: {
    name: "精炼剂",
    color: "#38bdf8",
    description: "特殊的化学试剂，可将原油提炼成高品质燃油。",
    weight: 2,
    category: "material",
    stackable: true,
  },
  轮胎: {
    name: "轮胎",
    color: "#1f2937",
    description: "耐磨的轮胎，可以大幅提升皮卡的耐久度。",
    weight: 12,
    category: "consumable",
    useEffect: { durability: 35 },
    stackable: true,
  },
  电池: {
    name: "电池",
    color: "#fbbf24",
    description: "高能电池，可以为各种装置提供动力。",
    weight: 2,
    category: "material",
    stackable: true,
  },
  橡胶: {
    name: "橡胶",
    color: "#6b7280",
    description: "天然橡胶，用于制作轮胎和密封件。",
    weight: 3,
    category: "material",
    stackable: true,
  },
  皮革: {
    name: "皮革",
    color: "#92400e",
    description: "柔软的皮革，可以制作高档坐垫和装饰品。",
    weight: 2,
    category: "material",
    stackable: true,
  },
  铜线: {
    name: "铜线",
    color: "#b45309",
    description: "导电的铜线，用于电气维修。",
    weight: 1,
    category: "material",
    stackable: true,
  },
  豪华坐垫: {
    name: "豪华坐垫",
    color: "#d946ef",
    description: "采用高档皮革和棉麻制成，极其舒适。",
    weight: 5,
    category: "consumable",
    useEffect: { comfort: 35 },
    stackable: true,
  },
  水冷系统: {
    name: "水冷系统",
    color: "#06b6d4",
    description: "先进的冷却系统，显著提升车辆耐久性。",
    weight: 15,
    category: "consumable",
    useEffect: { durability: 50 },
    stackable: false,
  },
  应急信号弹: {
    name: "应急信号弹",
    color: "#ef4444",
    description: "紧急求救装置，可以在危难时刻吸引援救。",
    weight: 2,
    category: "special",
    stackable: true,
  },
  鹰眼地图: {
    name: "鹰眼地图",
    color: "#7c3aed",
    description: "标注了所有隐藏地点的古老地图。",
    weight: 1,
    category: "special",
    stackable: false,
  },

  // === 高级合成成品===
  超级修理包: {
    name: "超级修理包",
    color: "#10b981",
    description: "用电气焊接技术强化的修理套件，修复效果远超普通修理包。",
    weight: 8,
    category: "consumable",
    useEffect: { durability: 60 },
    stackable: true,
  },
  燃油混合液: {
    name: "燃油混合液",
    color: "#f59e0b",
    description: "原油与精炼剂的高效混合燃油，燃烧效率极高。",
    weight: 12,
    category: "consumable",
    useEffect: { fuel: 80 },
    stackable: true,
  },
  医疗补给包: {
    name: "医疗补给包",
    color: "#fb7185",
    description: "综合性野外医疗包，同时恢复车辆状态与乘客精神。",
    weight: 6,
    category: "consumable",
    useEffect: { durability: 25, comfort: 35 },
    stackable: true,
  },
  舒适组合包: {
    name: "舒适组合包",
    color: "#a78bfa",
    description:
      "特调的旅途舒适礼包，零食、坐垫、布料的完美组合，让车内气氛愉快极了。",
    weight: 7,
    category: "consumable",
    useEffect: { comfort: 50 },
    stackable: true,
  },

  // === 乘客专属物品（通过乘客特殊事件获取）===
  鹿角护符: {
    name: "鹿角护符",
    color: "#d4a574",
    description:
      "鹿用鹿角亲手制成的护符。蕴含着自然的力量，同时恢复燃油、舒适与耐久。",
    weight: 1,
    category: "special",
    useEffect: { fuel: 30, comfort: 30, durability: 25 },
    stackable: false,
  },
  猎人徽章: {
    name: "猎人徽章",
    color: "#8b7355",
    description:
      "猎人传下的勋章，象征野外生存的极限智慧。用于紧急维修时效果惊人。",
    weight: 2,
    category: "special",
    useEffect: { durability: 70 },
    stackable: false,
  },
  骚福瑞手办: {
    name: "骚福瑞手办",
    color: "#ff69b4",
    description:
      "派对现场粉丝亲手制作的骚福瑞限定手办。看着它，车内所有人都会莫名陷入极度愉悦。",
    weight: 1,
    category: "special",
    useEffect: { comfort: 80 },
    stackable: false,
  },
  和平徽章: {
    name: "和平徽章",
    color: "#10b981",
    description:
      "鹿与猎人共同认可的徽章，象征对立者的和解。佩戴时能带来内心的平静与和谐。",
    weight: 1,
    category: "special",
    useEffect: { comfort: 20, durability: 15 },
    stackable: false,
  },
};

// 合成配方
const CRAFTING_RECIPES = {
  修理包: {
    name: "修理包",
    materials: [{ itemId: "废金属", quantity: 2 }],
    result: { itemId: "修理包", quantity: 1 },
  },
  坐垫: {
    name: "坐垫",
    materials: [{ itemId: "布料", quantity: 3 }],
    result: { itemId: "坐垫", quantity: 1 },
  },
  急救箱: {
    name: "急救箱",
    materials: [
      { itemId: "草药", quantity: 2 },
      { itemId: "布料", quantity: 1 },
    ],
    result: { itemId: "急救箱", quantity: 1 },
  },
  油桶: {
    name: "油桶",
    materials: [
      { itemId: "空罐", quantity: 1 },
      { itemId: "原油", quantity: 1 },
    ],
    result: { itemId: "油桶", quantity: 1 },
  },
  高级燃油: {
    name: "高级燃油",
    materials: [
      { itemId: "空罐", quantity: 1 },
      { itemId: "原油", quantity: 1 },
      { itemId: "精炼剂", quantity: 1 },
    ],
    result: { itemId: "高级燃油", quantity: 1 },
  },
  轮胎: {
    name: "轮胎",
    materials: [
      { itemId: "橡胶", quantity: 3 },
      { itemId: "废金属", quantity: 1 },
    ],
    result: { itemId: "轮胎", quantity: 1 },
    difficulty: "高",
  },
  豪华坐垫: {
    name: "豪华坐垫",
    materials: [
      { itemId: "皮革", quantity: 2 },
      { itemId: "布料", quantity: 3 },
      { itemId: "精炼剂", quantity: 1 },
    ],
    result: { itemId: "豪华坐垫", quantity: 1 },
    difficulty: "高",
  },
  超级修理包: {
    name: "超级修理包",
    materials: [
      { itemId: "废金属", quantity: 4 },
      { itemId: "电池", quantity: 2 },
      { itemId: "铜线", quantity: 3 },
    ],
    result: { itemId: "超级修理包", quantity: 1 },
    difficulty: "高",
  },
  燃油混合液: {
    name: "燃油混合液",
    materials: [
      { itemId: "原油", quantity: 2 },
      { itemId: "精炼剂", quantity: 2 },
      { itemId: "电池", quantity: 1 },
    ],
    result: { itemId: "燃油混合液", quantity: 1 },
    difficulty: "高",
  },
  医疗补给包: {
    name: "医疗补给包",
    materials: [
      { itemId: "草药", quantity: 4 },
      { itemId: "布料", quantity: 2 },
      { itemId: "零食", quantity: 3 },
    ],
    result: { itemId: "医疗补给包", quantity: 1 },
    difficulty: "中",
  },
  舒适组合包: {
    name: "舒适组合包",
    materials: [
      { itemId: "坐垫", quantity: 1 },
      { itemId: "零食", quantity: 5 },
      { itemId: "布料", quantity: 2 },
    ],
    result: { itemId: "舒适组合包", quantity: 1 },
    difficulty: "低",
  },
};
